version: "1"
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Pasuwok@123 # Root password for MySQL
      MYSQL_DATABASE: book-review        # Database name to create
    ports:
      - "3306:3306" # Maps the container's MySQL port to the host
    volumes:
      - db_data:/var/lib/mysql # Persist data in a named volume
  app:
    image: book-review
    ports:
      - 8000:6500
    env_file:
      - .env

volumes:
  db_data:
