version: "1"
services:
  db:
    image: mysql
    environment:
      - DB_DIALECT='mysql'
      - DB_HOST='127.0.0.1'
      - DB_USERNAME='root'
      - DB_PASSWORD='Pasuwok@123'
      - DB_DATABASE='book-review'
      - DB_PORT=3306
  app:
    image: bookReview
    port:
      8000:6500